### ISSUE TITLE
Add linter of some sort

### ISSUE THREAD

**Issue by isakal** [vivax3794/python_twitch_bot#4]
Adding a linter would help with maintaining consistent code style between multiple contributors.
I suggest choosing [flake8](https://flake8.pycqa.org/en/latest/) as it's most supported linter and can be used with configuration file.

**Comment by vivax3794** [comment]
funny you mentioned it, I went over the code and linted and fixed some stuff.
but some sort of test on githubs side would be helpfull.

**Comment by vivax3794** [comment]
okay I setup a [workflow](https://github.com/vivax3794/python_twitch_bot/blob/master/.github/workflows/linting.yml) that should run flake8 and mypy on the project.

**Comment by isakal** [comment]
You could add the config file for easier local linting and to stop failed builds because of unlinted code.

**Comment by isakal** [comment]
I added the config file for flake8 in the [latest commit](https://github.com/vivax3794/python_twitch_bot/commit/566036714e7a690ef6fcfdeee5f10eb728d7c3bf).
It just checks for errors and warnings specified in the workflow file.
I would like to add further code style checks, @vivax3794 let me know what you think.

**Comment by vivax3794** [comment]
sure, sounds good.
 I dont have much experience with setting up linters for projects like this, so thanks :)

**Comment by isakal** [comment]
I added `.flake8` file and fixed everything that flake8 was complaining in the last commit.
